// This script fills your MongoDB database with sample products so you can
// see the app working immediately. Run it with:
//
//     npm run seed        (from inside the server/ folder)
//
// It deletes any existing products first, then inserts the sample list below.
// Replace the "images" paths with your own files once you've added them to
// local-assets/images/<category>/ - see the README for details.

require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("../config/db");
const Product = require("../models/Product");

const products = [
    // ---------------- MEN ----------------
    {
        name: "Tailored Fit Blazer",
        brand: "Urban Thread",
        category: "men",
        subCategory: "blazers",
        gender: "men",
        price: 2999,
        originalPrice: 4999,
        discount: 40,
        description: "A tailored fit blazer that adds a sharp edge to formal and semi-formal outfits.",
        material: "Polyester Blend",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Navy", "Black"],
        images: ["/local-assets/images/men/men-blazer1.jpg"],
        rating: 4.5,
        reviews: 47,
        stock: 15
    },
    {
        name: "Formal Slim Fit Shirt",
        brand: "Urban Thread",
        category: "men",
        subCategory: "shirts",
        gender: "men",
        price: 1099,
        originalPrice: 1799,
        discount: 39,
        description: "A crisp formal shirt with a slim fit, ideal for office wear.",
        material: "Cotton Blend",
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Sky Blue"],
        images: ["/local-assets/images/men/men-formal1.jpg"],
        rating: 4.3,
        reviews: 68,
        stock: 28
    },
    {
        name: "Fleece Pullover Hoodie",
        brand: "Streetline",
        category: "men",
        subCategory: "hoodies",
        gender: "men",
        price: 999,
        originalPrice: 1599,
        discount: 38,
        description: "A cozy fleece hoodie with a kangaroo pocket, great for layering.",
        material: "Fleece",
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Grey", "Black"],
        images: ["/local-assets/images/men/men-hoodie1.jpg"],
        rating: 4.4,
        reviews: 91,
        stock: 33
    },
    {
        name: "Bomber Jacket",
        brand: "Streetline",
        category: "men",
        subCategory: "jackets",
        gender: "men",
        price: 1799,
        originalPrice: 2999,
        discount: 40,
        description: "A classic bomber jacket with ribbed cuffs, perfect for cooler weather.",
        material: "Polyester",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Olive"],
        images: ["/local-assets/images/men/men-jacket1.jpg"],
        rating: 4.5,
        reviews: 54,
        stock: 20
    },
    {
        name: "Straight Fit Jeans",
        brand: "Denim Co.",
        category: "men",
        subCategory: "jeans",
        gender: "men",
        price: 1399,
        originalPrice: 2299,
        discount: 39,
        description: "Durable straight fit jeans with a timeless, versatile look.",
        material: "Denim",
        sizes: ["30", "32", "34", "36"],
        colors: ["Blue", "Black"],
        images: ["/local-assets/images/men/men-jean1.jpg"],
        rating: 4.1,
        reviews: 76,
        stock: 24
    },
    {
        name: "Ethnic Cotton Kurta",
        brand: "Ethnic Roots",
        category: "men",
        subCategory: "ethnic wear",
        gender: "men",
        price: 999,
        originalPrice: 1699,
        discount: 41,
        description: "A comfortable cotton kurta suited for festive and casual occasions.",
        material: "Cotton",
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Beige"],
        images: ["/local-assets/images/men/men-kurta1.jpg"],
        rating: 4.3,
        reviews: 39,
        stock: 22
    },
    {
        name: "Checked Casual Shirt",
        brand: "Urban Thread",
        category: "men",
        subCategory: "shirts",
        gender: "men",
        price: 849,
        originalPrice: 1399,
        discount: 39,
        description: "A relaxed-fit checked shirt that works well for casual outings.",
        material: "Cotton",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Blue", "Green"],
        images: ["/local-assets/images/men/men-shirt1.jpg"],
        rating: 4.2,
        reviews: 58,
        stock: 30
    },
    {
        name: "Cargo Shorts",
        brand: "Streetline",
        category: "men",
        subCategory: "shorts",
        gender: "men",
        price: 649,
        originalPrice: 999,
        discount: 35,
        description: "Utility cargo shorts with multiple pockets, built for everyday comfort.",
        material: "Cotton Blend",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Khaki", "Black"],
        images: ["/local-assets/images/men/men-short1.jpg"],
        rating: 4.0,
        reviews: 34,
        stock: 42
    },
    {
        name: "Men's Tracksuit Set",
        brand: "SprintFit",
        category: "men",
        subCategory: "sportswear",
        gender: "men",
        price: 1399,
        originalPrice: 2199,
        discount: 36,
        description: "A comfortable tracksuit set designed for workouts and casual wear alike.",
        material: "Polyester Blend",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Navy", "Grey"],
        images: ["/local-assets/images/men/men-tracksuit1.jpg"],
        rating: 4.4,
        reviews: 62,
        stock: 26
    },
    {
        name: "Solid Round Neck T-Shirt",
        brand: "Streetline",
        category: "men",
        subCategory: "tshirts",
        gender: "men",
        price: 449,
        originalPrice: 699,
        discount: 36,
        description: "A soft, breathable solid t-shirt that's a wardrobe essential.",
        material: "Cotton",
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Black", "Navy"],
        images: ["/local-assets/images/men/men-tshirt1.jpg"],
        rating: 4.3,
        reviews: 97,
        stock: 45
    },

    // ---------------- WOMEN ----------------
    {
        name: "Wrap Midi Dress",
        brand: "Bloom Studio",
        category: "women",
        subCategory: "dresses",
        gender: "women",
        price: 1399,
        originalPrice: 2499,
        discount: 44,
        description: "A flattering wrap midi dress suited for both casual and semi-formal occasions.",
        material: "Rayon",
        sizes: ["XS", "S", "M", "L"],
        colors: ["Maroon", "Navy"],
        images: ["/local-assets/images/women/women-dress1.jpg"],
        rating: 4.4,
        reviews: 52,
        stock: 18
    },
    {
        name: "Oversized Pullover Hoodie",
        brand: "Streetline",
        category: "women",
        subCategory: "western wear",
        gender: "women",
        price: 999,
        originalPrice: 1599,
        discount: 38,
        description: "A cozy oversized hoodie that pairs well with jeans or leggings.",
        material: "Fleece",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Grey", "Beige"],
        images: ["/local-assets/images/women/women-hoodie1.jpg"],
        rating: 4.3,
        reviews: 46,
        stock: 27
    },
    {
        name: "Quilted Bomber Jacket",
        brand: "Bloom Studio",
        category: "women",
        subCategory: "western wear",
        gender: "women",
        price: 1699,
        originalPrice: 2799,
        discount: 39,
        description: "A quilted bomber jacket that adds a stylish layer for cooler days.",
        material: "Polyester",
        sizes: ["XS", "S", "M", "L"],
        colors: ["Black", "Olive"],
        images: ["/local-assets/images/women/women-jacket1.jpg"],
        rating: 4.4,
        reviews: 35,
        stock: 16
    },
    {
        name: "Bootcut Denim Jeans",
        brand: "Denim Co.",
        category: "women",
        subCategory: "jeans",
        gender: "women",
        price: 1199,
        originalPrice: 2099,
        discount: 43,
        description: "Classic bootcut jeans with a flattering fit through the hip and thigh.",
        material: "Denim",
        sizes: ["26", "28", "30", "32"],
        colors: ["Blue"],
        images: ["/local-assets/images/women/women-jean1.jpg"],
        rating: 4.1,
        reviews: 41,
        stock: 23
    },
    {
        name: "Printed Straight Kurti",
        brand: "Ethnic Roots",
        category: "women",
        subCategory: "kurtis",
        gender: "women",
        price: 699,
        originalPrice: 1199,
        discount: 42,
        description: "A printed straight-cut kurti made from breathable fabric, ideal for daily wear.",
        material: "Cotton",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Blue", "Mustard"],
        images: ["/local-assets/images/women/women-kurti1.jpg"],
        rating: 4.2,
        reviews: 58,
        stock: 29
    },
    {
        name: "Ankle Length Leggings",
        brand: "Bloom Studio",
        category: "women",
        subCategory: "western wear",
        gender: "women",
        price: 349,
        originalPrice: 599,
        discount: 42,
        description: "Stretchable ankle-length leggings that pair easily with kurtis and tunics.",
        material: "Cotton Lycra",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Navy"],
        images: ["/local-assets/images/women/women-leggin1.jpg"],
        rating: 4.0,
        reviews: 63,
        stock: 48
    },
    {
        name: "Banarasi Silk Saree",
        brand: "Ethnic Roots",
        category: "women",
        subCategory: "sarees",
        gender: "women",
        price: 2499,
        originalPrice: 4499,
        discount: 44,
        description: "A rich Banarasi silk saree with intricate woven detailing, perfect for festive occasions.",
        material: "Silk Blend",
        sizes: ["Free Size"],
        colors: ["Red", "Gold"],
        images: ["/local-assets/images/women/women-saree1.jpg"],
        rating: 4.6,
        reviews: 27,
        stock: 10
    },
    {
        name: "A-Line Denim Skirt",
        brand: "Denim Co.",
        category: "women",
        subCategory: "western wear",
        gender: "women",
        price: 799,
        originalPrice: 1299,
        discount: 38,
        description: "An A-line denim skirt with a comfortable stretch fit.",
        material: "Denim",
        sizes: ["XS", "S", "M", "L"],
        colors: ["Blue"],
        images: ["/local-assets/images/women/women-skirt1.jpg"],
        rating: 4.1,
        reviews: 32,
        stock: 21
    },
    {
        name: "Casual Cotton Top",
        brand: "Bloom Studio",
        category: "women",
        subCategory: "tops",
        gender: "women",
        price: 549,
        originalPrice: 899,
        discount: 39,
        description: "A breathable cotton top that works well for both casual and office wear.",
        material: "Cotton",
        sizes: ["XS", "S", "M", "L"],
        colors: ["White", "Blush"],
        images: ["/local-assets/images/women/women-top1.jpg"],
        rating: 4.2,
        reviews: 49,
        stock: 34
    },
    {
        name: "Graphic Print T-Shirt",
        brand: "Streetline",
        category: "women",
        subCategory: "tshirts",
        gender: "women",
        price: 449,
        originalPrice: 699,
        discount: 36,
        description: "A relaxed-fit graphic tee made from soft cotton.",
        material: "Cotton",
        sizes: ["XS", "S", "M", "L"],
        colors: ["White", "Black"],
        images: ["/local-assets/images/women/women-tshirt1.jpg"],
        rating: 4.3,
        reviews: 71,
        stock: 39
    },

    // ---------------- KIDS ----------------
    {
        name: "Party Wear Kids Dress",
        brand: "Little Champs",
        category: "kids",
        subCategory: "girls",
        gender: "kids",
        price: 799,
        originalPrice: 1299,
        discount: 38,
        description: "A festive party wear dress with a soft lining, great for special occasions.",
        material: "Cotton Blend",
        sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
        colors: ["Pink", "Purple"],
        images: ["/local-assets/images/kids/kids-dress1.jpg"],
        rating: 4.4,
        reviews: 33,
        stock: 20
    },
    {
        name: "Fleece Hoodie",
        brand: "Little Champs",
        category: "kids",
        subCategory: "boys",
        gender: "kids",
        price: 649,
        originalPrice: 999,
        discount: 35,
        description: "A warm fleece hoodie with a front kangaroo pocket, perfect for cooler days.",
        material: "Fleece",
        sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
        colors: ["Grey", "Navy"],
        images: ["/local-assets/images/kids/kids-hoodie1.jpg"],
        rating: 4.3,
        reviews: 41,
        stock: 26
    },
    {
        name: "Kids Puffer Jacket",
        brand: "Little Champs",
        category: "kids",
        subCategory: "boys",
        gender: "kids",
        price: 1199,
        originalPrice: 1899,
        discount: 37,
        description: "A lightweight puffer jacket that keeps kids warm without weighing them down.",
        material: "Polyester",
        sizes: ["4-5Y", "6-7Y", "8-9Y"],
        colors: ["Blue", "Black"],
        images: ["/local-assets/images/kids/kids-jacket1.jpg"],
        rating: 4.5,
        reviews: 29,
        stock: 18
    },
    {
        name: "Kids Regular Fit Jeans",
        brand: "Little Champs",
        category: "kids",
        subCategory: "boys",
        gender: "kids",
        price: 549,
        originalPrice: 899,
        discount: 39,
        description: "Comfortable regular fit jeans built for everyday play.",
        material: "Denim",
        sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
        colors: ["Blue"],
        images: ["/local-assets/images/kids/kids-jean1.jpg"],
        rating: 4.1,
        reviews: 37,
        stock: 32
    },
    {
        name: "Kids Ethnic Kurta Set",
        brand: "Ethnic Roots",
        category: "kids",
        subCategory: "girls",
        gender: "kids",
        price: 699,
        originalPrice: 1199,
        discount: 42,
        description: "A traditional kurta set for festive occasions, made from breathable cotton.",
        material: "Cotton",
        sizes: ["2-3Y", "4-5Y", "6-7Y"],
        colors: ["Yellow", "Green"],
        images: ["/local-assets/images/kids/kids-kurta1.jpg"],
        rating: 4.4,
        reviews: 26,
        stock: 22
    },
    {
        name: "Cotton Pajama Set",
        brand: "Little Champs",
        category: "kids",
        subCategory: "girls",
        gender: "kids",
        price: 449,
        originalPrice: 699,
        discount: 36,
        description: "A soft cotton pajama set designed for comfortable sleep.",
        material: "Cotton",
        sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
        colors: ["Blue", "Pink"],
        images: ["/local-assets/images/kids/kids-pajama1.jpg"],
        rating: 4.2,
        reviews: 45,
        stock: 34
    },
    {
        name: "Printed Cotton Shorts",
        brand: "Little Champs",
        category: "kids",
        subCategory: "boys",
        gender: "kids",
        price: 299,
        originalPrice: 499,
        discount: 40,
        description: "Breathable printed shorts, ideal for warm weather and outdoor play.",
        material: "Cotton",
        sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
        colors: ["Blue", "Grey"],
        images: ["/local-assets/images/kids/kids-short1.jpg"],
        rating: 4.0,
        reviews: 22,
        stock: 40
    },
    {
        name: "Pleated Denim Skirt",
        brand: "Little Champs",
        category: "kids",
        subCategory: "girls",
        gender: "kids",
        price: 499,
        originalPrice: 799,
        discount: 38,
        description: "A pleated denim skirt with an adjustable waist for a comfortable fit.",
        material: "Denim",
        sizes: ["2-3Y", "4-5Y", "6-7Y"],
        colors: ["Blue"],
        images: ["/local-assets/images/kids/kids-skirt1.jpg"],
        rating: 4.1,
        reviews: 18,
        stock: 25
    },
    {
        name: "Kids Tracksuit Set",
        brand: "SprintFit",
        category: "kids",
        subCategory: "boys",
        gender: "kids",
        price: 899,
        originalPrice: 1399,
        discount: 36,
        description: "A comfortable tracksuit set made for active play and sports.",
        material: "Polyester Blend",
        sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
        colors: ["Navy", "Grey"],
        images: ["/local-assets/images/kids/kids-tracksuit1.jpg"],
        rating: 4.3,
        reviews: 31,
        stock: 24
    },
    {
        name: "Kids Graphic T-Shirt",
        brand: "Little Champs",
        category: "kids",
        subCategory: "girls",
        gender: "kids",
        price: 349,
        originalPrice: 549,
        discount: 36,
        description: "A fun graphic t-shirt made from soft, skin-friendly cotton.",
        material: "Cotton",
        sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
        colors: ["White", "Pink"],
        images: ["/local-assets/images/kids/kids-tshirt1.jpg"],
        rating: 4.2,
        reviews: 39,
        stock: 36
    },

    // ---------------- FOOTWEAR ----------------
    {
        name: "Running Sports Sneakers",
        brand: "SprintFit",
        category: "footwear",
        subCategory: "sneakers",
        gender: "unisex",
        price: 1799,
        originalPrice: 2999,
        discount: 40,
        description: "Lightweight running sneakers with cushioned soles for all-day comfort.",
        material: "Mesh & Rubber",
        sizes: ["6", "7", "8", "9", "10"],
        colors: ["White", "Black"],
        images: ["/local-assets/images/footwear/sneaker1.jpg"],
        rating: 4.4,
        reviews: 302,
        stock: 35
    },
    {
        name: "Women's Block Heel Sandals",
        brand: "StepStyle",
        category: "footwear",
        subCategory: "sandals",
        gender: "women",
        price: 999,
        originalPrice: 1799,
        discount: 44,
        description: "Comfortable block heel sandals for a polished everyday look.",
        material: "Synthetic Leather",
        sizes: ["5", "6", "7", "8"],
        colors: ["Black", "Tan"],
        images: ["/local-assets/images/footwear/sandal1.jpg"],
        rating: 4.0,
        reviews: 63,
        stock: 20
    },
    {
        name: "Ankle Length Winter Boot",
        brand: "StepStyle",
        category: "footwear",
        subCategory: "boots",
        gender: "women",
        price: 1899,
        originalPrice: 2999,
        discount: 37,
        description: "A sturdy ankle-length boot with a comfortable sole, great for colder days.",
        material: "Synthetic Leather",
        sizes: ["5", "6", "7", "8"],
        colors: ["Black", "Brown"],
        images: ["/local-assets/images/footwear/boot1.jpg"],
        rating: 4.3,
        reviews: 58,
        stock: 22
    },
    {
        name: "Everyday Ballet Flats",
        brand: "StepStyle",
        category: "footwear",
        subCategory: "flats",
        gender: "women",
        price: 799,
        originalPrice: 1299,
        discount: 38,
        description: "Soft, lightweight ballet flats designed for all-day comfort.",
        material: "Synthetic Leather",
        sizes: ["5", "6", "7", "8"],
        colors: ["Black", "Nude"],
        images: ["/local-assets/images/footwear/flat1.jpg"],
        rating: 4.1,
        reviews: 47,
        stock: 36
    },
    {
        name: "Casual Flip-Flops",
        brand: "SprintFit",
        category: "footwear",
        subCategory: "sandals",
        gender: "unisex",
        price: 299,
        originalPrice: 499,
        discount: 40,
        description: "Lightweight, quick-drying flip-flops perfect for casual everyday wear.",
        material: "EVA Foam",
        sizes: ["6", "7", "8", "9", "10"],
        colors: ["Blue", "Black"],
        images: ["/local-assets/images/footwear/flip-flop1.jpg"],
        rating: 3.9,
        reviews: 41,
        stock: 60
    },
    {
        name: "Formal Oxford Shoes",
        brand: "CraftHide",
        category: "footwear",
        subCategory: "formal shoes",
        gender: "men",
        price: 2199,
        originalPrice: 3499,
        discount: 37,
        description: "Classic formal oxford shoes crafted for a sharp, polished look.",
        material: "Genuine Leather",
        sizes: ["7", "8", "9", "10", "11"],
        colors: ["Black", "Brown"],
        images: ["/local-assets/images/footwear/formal-shoe1.jpg"],
        rating: 4.5,
        reviews: 89,
        stock: 18
    },
    {
        name: "Strappy Block Heels",
        brand: "StepStyle",
        category: "footwear",
        subCategory: "heels",
        gender: "women",
        price: 1299,
        originalPrice: 2199,
        discount: 41,
        description: "Elegant strappy block heels that balance comfort with style for evening wear.",
        material: "Synthetic Leather",
        sizes: ["5", "6", "7", "8"],
        colors: ["Black", "Nude", "Red"],
        images: ["/local-assets/images/footwear/heel1.jpg"],
        rating: 4.2,
        reviews: 53,
        stock: 24
    },
    {
        name: "Slip-On Leather Loafers",
        brand: "CraftHide",
        category: "footwear",
        subCategory: "loafers",
        gender: "men",
        price: 1599,
        originalPrice: 2599,
        discount: 38,
        description: "Comfortable slip-on loafers made from smooth leather, ideal for smart-casual looks.",
        material: "Genuine Leather",
        sizes: ["7", "8", "9", "10", "11"],
        colors: ["Brown", "Tan"],
        images: ["/local-assets/images/footwear/loafer1.jpg"],
        rating: 4.3,
        reviews: 66,
        stock: 27
    },
    {
        name: "Lightweight Running Shoes",
        brand: "SprintFit",
        category: "footwear",
        subCategory: "sneakers",
        gender: "unisex",
        price: 2099,
        originalPrice: 3299,
        discount: 36,
        description: "Breathable running shoes built for long-distance comfort and support.",
        material: "Mesh & Rubber",
        sizes: ["6", "7", "8", "9", "10"],
        colors: ["Grey", "Blue"],
        images: ["/local-assets/images/footwear/running-shoe1.jpg"],
        rating: 4.6,
        reviews: 214,
        stock: 33
    },
    {
        name: "Cushioned Home Slippers",
        brand: "HomeComfort",
        category: "footwear",
        subCategory: "slippers",
        gender: "unisex",
        price: 349,
        originalPrice: 599,
        discount: 42,
        description: "Soft, cushioned slippers designed for everyday comfort at home.",
        material: "EVA Foam",
        sizes: ["Free Size"],
        colors: ["Grey", "Beige"],
        images: ["/local-assets/images/footwear/slipper1.jpg"],
        rating: 4.0,
        reviews: 35,
        stock: 48
    },

    // ---------------- BEAUTY ----------------
    {
        name: "Matte Finish Lipstick",
        brand: "GlowUp Cosmetics",
        category: "beauty",
        subCategory: "makeup",
        gender: "unisex",
        price: 349,
        originalPrice: 499,
        discount: 30,
        description: "Long-lasting matte lipstick available in vibrant shades.",
        material: "",
        sizes: [],
        colors: ["Red", "Pink"],
        images: ["/local-assets/images/beauty/lipstick1.jpg"],
        rating: 4.3,
        reviews: 189,
        stock: 60
    },
    {
        name: "Hydrating Face Serum",
        brand: "PureGlow",
        category: "beauty",
        subCategory: "skincare",
        gender: "unisex",
        price: 599,
        originalPrice: 899,
        discount: 33,
        description: "Lightweight face serum that hydrates and brightens skin.",
        material: "",
        sizes: [],
        colors: [],
        images: ["/local-assets/images/beauty/serum1.jpg"],
        rating: 4.6,
        reviews: 275,
        stock: 45
    },
    {
        name: "Soft Matte Blush",
        brand: "GlowUp Cosmetics",
        category: "beauty",
        subCategory: "makeup",
        gender: "unisex",
        price: 399,
        originalPrice: 599,
        discount: 33,
        description: "A soft, buildable blush that adds a natural flush of color to the cheeks.",
        material: "",
        sizes: [],
        colors: ["Peach", "Rose"],
        images: ["/local-assets/images/beauty/blush1.jpg"],
        rating: 4.2,
        reviews: 58,
        stock: 40
    },
    {
        name: "Full Coverage Concealer",
        brand: "PureGlow",
        category: "beauty",
        subCategory: "makeup",
        gender: "unisex",
        price: 449,
        originalPrice: 699,
        discount: 36,
        description: "A creamy, full coverage concealer that blends easily and hides blemishes.",
        material: "",
        sizes: [],
        colors: ["Light", "Medium", "Deep"],
        images: ["/local-assets/images/beauty/concealer1.jpg"],
        rating: 4.4,
        reviews: 91,
        stock: 34
    },
    {
        name: "Precision Liquid Eyeliner",
        brand: "GlowUp Cosmetics",
        category: "beauty",
        subCategory: "makeup",
        gender: "unisex",
        price: 299,
        originalPrice: 499,
        discount: 40,
        description: "A precision-tip liquid eyeliner for sharp, long-lasting lines.",
        material: "",
        sizes: [],
        colors: ["Black"],
        images: ["/local-assets/images/beauty/eyeliner1.jpg"],
        rating: 4.5,
        reviews: 122,
        stock: 55
    },
    {
        name: "Everyday Eyeshadow Palette",
        brand: "GlowUp Cosmetics",
        category: "beauty",
        subCategory: "makeup",
        gender: "unisex",
        price: 799,
        originalPrice: 1299,
        discount: 38,
        description: "A versatile eyeshadow palette with matte and shimmer shades for everyday looks.",
        material: "",
        sizes: [],
        colors: ["Neutral Tones"],
        images: ["/local-assets/images/beauty/eyeshadow-palette1.jpg"],
        rating: 4.6,
        reviews: 143,
        stock: 26
    },
    {
        name: "Natural Finish Foundation",
        brand: "PureGlow",
        category: "beauty",
        subCategory: "makeup",
        gender: "unisex",
        price: 649,
        originalPrice: 999,
        discount: 35,
        description: "A lightweight foundation that evens out skin tone with a natural finish.",
        material: "",
        sizes: [],
        colors: ["Light", "Medium", "Deep"],
        images: ["/local-assets/images/beauty/foundation1.jpg"],
        rating: 4.3,
        reviews: 108,
        stock: 37
    },
    {
        name: "Smoothing Makeup Primer",
        brand: "PureGlow",
        category: "beauty",
        subCategory: "makeup",
        gender: "unisex",
        price: 549,
        originalPrice: 849,
        discount: 35,
        description: "A silky primer that smooths pores and helps makeup last longer.",
        material: "",
        sizes: [],
        colors: [],
        images: ["/local-assets/images/beauty/makeup-primer1.jpg"],
        rating: 4.4,
        reviews: 76,
        stock: 30
    },
    {
        name: "Volumizing Mascara",
        brand: "GlowUp Cosmetics",
        category: "beauty",
        subCategory: "makeup",
        gender: "unisex",
        price: 349,
        originalPrice: 549,
        discount: 36,
        description: "A volumizing mascara that lifts and defines lashes without clumping.",
        material: "",
        sizes: [],
        colors: ["Black"],
        images: ["/local-assets/images/beauty/mascara1.jpg"],
        rating: 4.5,
        reviews: 167,
        stock: 48
    },
    {
        name: "Glossy Nail Polish",
        brand: "GlowUp Cosmetics",
        category: "beauty",
        subCategory: "makeup",
        gender: "unisex",
        price: 199,
        originalPrice: 349,
        discount: 43,
        description: "A high-shine, quick-dry nail polish available in a range of colors.",
        material: "",
        sizes: [],
        colors: ["Red", "Nude", "Coral"],
        images: ["/local-assets/images/beauty/nail-polish1.jpg"],
        rating: 4.1,
        reviews: 64,
        stock: 52
    },

    // ---------------- ACCESSORIES ----------------
    {
        name: "Analog Wrist Watch",
        brand: "TimeCraft",
        category: "accessories",
        subCategory: "watches",
        gender: "unisex",
        price: 1499,
        originalPrice: 2499,
        discount: 40,
        description: "A minimalist analog watch with a genuine leather strap.",
        material: "Leather & Stainless Steel",
        sizes: [],
        colors: ["Brown", "Black"],
        images: ["/local-assets/images/accessories/watch1.jpg"],
        rating: 4.2,
        reviews: 97,
        stock: 28
    },
    {
        name: "Canvas Tote Bag",
        brand: "CarryAll",
        category: "accessories",
        subCategory: "bags",
        gender: "women",
        price: 699,
        originalPrice: 999,
        discount: 30,
        description: "A spacious canvas tote bag, great for daily use.",
        material: "Canvas",
        sizes: [],
        colors: ["Beige", "Black"],
        images: ["/local-assets/images/accessories/bag1.jpg"],
        rating: 4.1,
        reviews: 54,
        stock: 33
    },
    {
        name: "Genuine Leather Belt",
        brand: "CraftHide",
        category: "accessories",
        subCategory: "belts",
        gender: "men",
        price: 599,
        originalPrice: 999,
        discount: 40,
        description: "A durable leather belt with a classic buckle, suited for both formal and casual wear.",
        material: "Genuine Leather",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Brown"],
        images: ["/local-assets/images/accessories/belt1.jpg"],
        rating: 4.2,
        reviews: 61,
        stock: 30
    },
    {
        name: "Beaded Charm Bracelet",
        brand: "Ornaya",
        category: "accessories",
        subCategory: "jewellery",
        gender: "women",
        price: 349,
        originalPrice: 599,
        discount: 42,
        description: "A delicate beaded bracelet with a small charm detail, great for everyday styling.",
        material: "Alloy & Glass Beads",
        sizes: [],
        colors: ["Gold", "Silver"],
        images: ["/local-assets/images/accessories/bracelet1.jpg"],
        rating: 4.0,
        reviews: 38,
        stock: 42
    },
    {
        name: "Cotton Baseball Cap",
        brand: "Streetline",
        category: "accessories",
        subCategory: "caps",
        gender: "unisex",
        price: 399,
        originalPrice: 699,
        discount: 43,
        description: "An adjustable cotton cap with a curved brim, perfect for everyday outdoor wear.",
        material: "Cotton",
        sizes: ["Free Size"],
        colors: ["Black", "Navy", "White"],
        images: ["/local-assets/images/accessories/cap1.jpg"],
        rating: 4.3,
        reviews: 84,
        stock: 50
    },
    {
        name: "Pearl Drop Earrings",
        brand: "Ornaya",
        category: "accessories",
        subCategory: "jewellery",
        gender: "women",
        price: 449,
        originalPrice: 799,
        discount: 44,
        description: "Elegant pearl drop earrings that add a subtle shine to any outfit.",
        material: "Alloy & Faux Pearl",
        sizes: [],
        colors: ["Gold", "Silver"],
        images: ["/local-assets/images/accessories/earring1.jpg"],
        rating: 4.4,
        reviews: 72,
        stock: 35
    },
    {
        name: "Layered Chain Necklace",
        brand: "Ornaya",
        category: "accessories",
        subCategory: "jewellery",
        gender: "women",
        price: 549,
        originalPrice: 999,
        discount: 45,
        description: "A layered chain necklace that pairs well with both casual and ethnic outfits.",
        material: "Alloy",
        sizes: [],
        colors: ["Gold", "Silver"],
        images: ["/local-assets/images/accessories/necklace1.jpg"],
        rating: 4.1,
        reviews: 45,
        stock: 27
    },
    {
        name: "Minimal Statement Ring",
        brand: "Ornaya",
        category: "accessories",
        subCategory: "jewellery",
        gender: "women",
        price: 299,
        originalPrice: 499,
        discount: 40,
        description: "A minimal statement ring with a clean, modern finish.",
        material: "Alloy",
        sizes: ["6", "7", "8", "9"],
        colors: ["Gold", "Silver"],
        images: ["/local-assets/images/accessories/ring.jpg"],
        rating: 4.0,
        reviews: 29,
        stock: 40
    },
    {
        name: "Classic Aviator Sunglasses",
        brand: "SunShade Co.",
        category: "accessories",
        subCategory: "sunglasses",
        gender: "unisex",
        price: 799,
        originalPrice: 1399,
        discount: 43,
        description: "UV-protected aviator sunglasses with a timeless metal frame.",
        material: "Metal & Polycarbonate",
        sizes: ["Free Size"],
        colors: ["Black", "Gold"],
        images: ["/local-assets/images/accessories/sunglass1.jpg"],
        rating: 4.3,
        reviews: 103,
        stock: 38
    },
    {
        name: "Bi-Fold Leather Wallet",
        brand: "CraftHide",
        category: "accessories",
        subCategory: "wallets",
        gender: "men",
        price: 649,
        originalPrice: 1099,
        discount: 41,
        description: "A compact bi-fold wallet with multiple card slots, crafted from genuine leather.",
        material: "Genuine Leather",
        sizes: [],
        colors: ["Black", "Brown"],
        images: ["/local-assets/images/accessories/wallet1.jpg"],
        rating: 4.2,
        reviews: 67,
        stock: 31
    },

    // ---------------- HOME & LIVING ----------------
    {
        name: "Cotton Bedsheet Set",
        brand: "HomeComfort",
        category: "home",
        subCategory: "bedsheets",
        gender: "unisex",
        price: 899,
        originalPrice: 1499,
        discount: 40,
        description: "Soft cotton bedsheet set with two matching pillow covers.",
        material: "Cotton",
        sizes: ["Single", "Double", "King"],
        colors: ["Blue", "Grey"],
        images: ["/local-assets/images/home/bedsheet1.jpg"],
        rating: 4.3,
        reviews: 71,
        stock: 26
    },
    {
        name: "Ceramic Table Vase",
        brand: "DecorNest",
        category: "home",
        subCategory: "decor",
        gender: "unisex",
        price: 449,
        originalPrice: 699,
        discount: 36,
        description: "A handcrafted ceramic vase to add a decorative touch to any room.",
        material: "Ceramic",
        sizes: [],
        colors: ["White"],
        images: ["/local-assets/images/home/vase1.jpg"],
        rating: 4.5,
        reviews: 39,
        stock: 17
    },
    {
        name: "3-Tier Wooden Book Shelf",
        brand: "DecorNest",
        category: "home",
        subCategory: "furniture",
        gender: "unisex",
        price: 2499,
        originalPrice: 3999,
        discount: 38,
        description: "A compact 3-tier book shelf that fits neatly into small living spaces.",
        material: "Engineered Wood",
        sizes: [],
        colors: ["Walnut", "White"],
        images: ["/local-assets/images/home/book-shelf1.jpg"],
        rating: 4.3,
        reviews: 44,
        stock: 12
    },
    {
        name: "Round Coffee Table",
        brand: "DecorNest",
        category: "home",
        subCategory: "furniture",
        gender: "unisex",
        price: 3299,
        originalPrice: 4999,
        discount: 34,
        description: "A round coffee table with a sturdy base, perfect for compact living rooms.",
        material: "Engineered Wood & Metal",
        sizes: [],
        colors: ["Walnut", "Black"],
        images: ["/local-assets/images/home/coffee-table1.jpg"],
        rating: 4.4,
        reviews: 37,
        stock: 10
    },
    {
        name: "Blackout Window Curtain",
        brand: "HomeComfort",
        category: "home",
        subCategory: "bath",
        gender: "unisex",
        price: 699,
        originalPrice: 1199,
        discount: 42,
        description: "A blackout curtain that blocks sunlight and adds a soft touch to any room.",
        material: "Polyester",
        sizes: ["Single Panel", "Set of 2"],
        colors: ["Grey", "Maroon", "Beige"],
        images: ["/local-assets/images/home/curtain1.jpg"],
        rating: 4.1,
        reviews: 52,
        stock: 30
    },
    {
        name: "6-Seater Dining Table Set",
        brand: "DecorNest",
        category: "home",
        subCategory: "furniture",
        gender: "unisex",
        price: 12999,
        originalPrice: 18999,
        discount: 32,
        description: "A spacious 6-seater dining table set crafted for family gatherings.",
        material: "Engineered Wood",
        sizes: [],
        colors: ["Walnut"],
        images: ["/local-assets/images/home/dining-table1.jpg"],
        rating: 4.5,
        reviews: 23,
        stock: 6
    },
    {
        name: "Adjustable Floor Lamp",
        brand: "DecorNest",
        category: "home",
        subCategory: "decor",
        gender: "unisex",
        price: 1599,
        originalPrice: 2499,
        discount: 36,
        description: "A modern floor lamp with an adjustable head, great for reading corners.",
        material: "Metal & Fabric",
        sizes: [],
        colors: ["Black", "Gold"],
        images: ["/local-assets/images/home/floor-lamp1.jpg"],
        rating: 4.2,
        reviews: 31,
        stock: 15
    },
    {
        name: "3-Seater Fabric Sofa",
        brand: "DecorNest",
        category: "home",
        subCategory: "furniture",
        gender: "unisex",
        price: 15999,
        originalPrice: 22999,
        discount: 30,
        description: "A comfortable 3-seater fabric sofa designed for everyday living room use.",
        material: "Fabric & Wood Frame",
        sizes: [],
        colors: ["Grey", "Beige"],
        images: ["/local-assets/images/home/sofa1.jpg"],
        rating: 4.6,
        reviews: 19,
        stock: 5
    },
    {
        name: "Minimalist Wall Clock",
        brand: "DecorNest",
        category: "home",
        subCategory: "decor",
        gender: "unisex",
        price: 599,
        originalPrice: 999,
        discount: 40,
        description: "A minimalist wall clock with a silent sweep mechanism.",
        material: "Metal & Glass",
        sizes: [],
        colors: ["Black", "White"],
        images: ["/local-assets/images/home/wall-clock1.jpg"],
        rating: 4.3,
        reviews: 48,
        stock: 28
    },
    {
        name: "3-Door Wooden Wardrobe",
        brand: "DecorNest",
        category: "home",
        subCategory: "furniture",
        gender: "unisex",
        price: 8999,
        originalPrice: 13999,
        discount: 35,
        description: "A spacious 3-door wardrobe with ample hanging and storage space.",
        material: "Engineered Wood",
        sizes: [],
        colors: ["Walnut", "White"],
        images: ["/local-assets/images/home/wardrobe1.jpg"],
        rating: 4.4,
        reviews: 21,
        stock: 8
    }
];

const seedProducts = async () => {
    try {
        await connectDB();

        // Remove all existing products before inserting fresh sample data
        await Product.deleteMany();
        console.log("Old products removed.");

        await Product.insertMany(products);
        console.log(products.length + " sample products added successfully.");

        mongoose.connection.close();
        process.exit(0);
    } catch (error) {
        console.error("Error seeding products:", error.message);
        process.exit(1);
    }
};

seedProducts();
